; Rename this file to "config.ini" after inserting your data

[API_KEY]
api_key = your_api_key

[IDs]
user_id = your_user_id
photoset_id = your_photoset_id
gallery_id = your_gallery_id

[PHOTOS]
number_photos = 15
option = 1

; Options:
; 1 - Get user's public photos (default)
; 2 - Get photos from user's photoset
; 3 - Get photos from a gallery
; 4 - Get user's favorite photos
; 5 - Get user's most popular photos