; Rename this file to "config.ini" after inserting your data

[API_KEY]
api_key = your_api_key

[IDs]
user_id = your_user_id
photoset_id = your_photoset_id
gallery_id = your_gallery_id

[PHOTOS]
photos_per_page = 15